default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: notification_service_development


test:
  <<: *default
  database: notification_service_test


production:
  primary: &primary_production
    <<: *default
    database: notification_service_production
    username: notification_service
    password: <%= ENV["NOTIFICATION_SERVICE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: notification_service_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: notification_service_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: notification_service_production_cable
    migrations_paths: db/cable_migrate
